import {test,expect} from '@playwright/test';
import {mkdtemp,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {releaseStates,checkSceneCoverage,runReleaseScenes} from '../../scripts/release-scenes.mjs';
import {fixtureHTML} from '../support/browser-fixture.js';
test('release states deterministically include all tier sides and 250 random views',()=>{const a=releaseStates({width:1000,height:800,features:[]});expect(a).toEqual(releaseStates({width:1000,height:800,features:[]}));expect(a.filter(x=>x.kind==='random')).toHaveLength(250);for(const boundary of [1.02,2,4.5])for(const delta of [-.0001,0,.0001])expect(a.some(s=>Math.abs(s.zoom-boundary-delta)<1e-8)).toBe(true);expect(a.some(s=>s.zoom===14)).toBe(true);});
test('coverage minima detect hidden names even when solver claims pass',()=>{const data={manifest:{annotations:[{id:'a',kind:'point-label',priority:800}]},visible:[],outcomes:[{id:'a',reason:'placed'}]};expect(checkSceneCoverage(data,{minima:{'point-label':1}})).toEqual([{kind:'point-label',minimum:1,visible:0}]);});
test('quick release harness independently rejects overlapping miniature map',async()=>{const dir=await mkdtemp(join(tmpdir(),'map-release-'));try{const input=join(dir,'map.html');await writeFile(input,(await fixtureHTML()).replaceAll('visibility:hidden','visibility:visible')+'<script>window.mapLayout={ready:Promise.resolve(),whenSettled:()=>Promise.resolve(),requestView:()=>{},result:{missingRequired:[]}};</script>');const r=await runReleaseScenes({input,reportDir:join(dir,'report'),browsers:['chromium'],viewports:[{width:768,height:1024}],dprs:[1],themes:['light'],states:[{id:'miniature',zoom:1,kind:'fixture'}],sampleCount:0,frameCount:0,interactions:false});expect(r.status).toBe('findings');expect(r.counts.overlaps).toBeGreaterThan(0);expect(r.artifactSha256).toMatch(/^[a-f0-9]{64}$/);expect(r.releaseComplete).toBe(false);}finally{await rm(dir,{recursive:true,force:true});}});
