import {test,expect} from '@playwright/test';
import {mkdtemp,writeFile,readFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {releaseStates,checkSceneCoverage,runReleaseScenes,checkPinnedTrailDetails} from '../../scripts/release-scenes.mjs';
import {summarizeCoverage} from '../../scripts/release-browser-audit.js';
import {runAudit} from '../../scripts/audit-map.mjs';
import {fixtureHTML} from '../support/browser-fixture.js';
test('release states deterministically include all tier sides and 250 random views',()=>{const a=releaseStates({width:1000,height:800,features:[]});expect(a).toEqual(releaseStates({width:1000,height:800,features:[]}));expect(a.filter(x=>x.kind==='random')).toHaveLength(250);for(const boundary of [1.02,2,4.5])for(const delta of [-.0001,0,.0001])expect(a.some(s=>Math.abs(s.zoom-boundary-delta)<1e-8)).toBe(true);expect(a.some(s=>s.zoom===14)).toBe(true);});
test('coverage minima detect hidden names even when solver claims pass',()=>{const data={manifest:{annotations:[{id:'a',kind:'point-label',priority:800}]},visible:[],outcomes:[{id:'a',reason:'placed'}]};expect(checkSceneCoverage(data,{minima:{'point-label':1}})).toEqual([{kind:'point-label',minimum:1,visible:0}]);});
test('quick release harness independently rejects overlapping miniature map',async()=>{const dir=await mkdtemp(join(tmpdir(),'map-release-'));try{const input=join(dir,'map.html');await writeFile(input,(await fixtureHTML()).replaceAll('visibility:hidden','visibility:visible').replaceAll('font-size:12px','font-size:6px')+'<img src="https://example.invalid/remote.png"><script>window.mapLayout={ready:Promise.resolve(),whenSettled:()=>Promise.resolve(),requestView:()=>{},result:{missingRequired:[]}};</script>');const r=await runReleaseScenes({input,reportDir:join(dir,'report'),browsers:['chromium'],viewports:[{width:768,height:1024}],dprs:[1],themes:['light'],states:[{id:'miniature',zoom:1,kind:'fixture'}],sampleCount:0,frameCount:2,interactions:false});expect(r.status,JSON.stringify(r.profiles)).toBe('findings');expect(r.counts.overlaps).toBeGreaterThan(0);expect(r.artifactSha256).toMatch(/^[a-f0-9]{64}$/);expect(r.releaseComplete).toBe(false);expect(r.profiles[0].networkFailures.some(f=>f.url.includes('example.invalid'))).toBe(true);expect(r.counts.incomplete).toBeGreaterThan(0);expect(r.counts.frames).toBe(6);expect(r.counts.typography).toBeGreaterThan(0);const audit=await runAudit({input,reportDir:join(dir,'audit'),mode:'managed'});expect(audit.counts.typography).toBeGreaterThan(0);for(const sample of r.profiles[0].samples){expect(sample.inventory).toBeUndefined();expect(sample.obstacles).toBeUndefined();expect(sample.counts.overlaps).toBeGreaterThan(0);}}finally{await rm(dir,{recursive:true,force:true});}});

test('desktop overview primary coverage uses eligible numerator and denominator',()=>{const data={manifest:{annotations:Array.from({length:10},(_,i)=>({id:String(i),kind:'point-label',priority:800}))},visible:['0','1','2'],outcomes:Array.from({length:10},(_,i)=>({id:String(i),eligible:i<8}))};const summary=summarizeCoverage(data);expect(summary['primary-point-label']).toEqual({visible:3,total:10,eligible:8,visibleEligible:3});const scene={viewportWidth:1440,fractions:[{kind:'primary-point-label',minimumFraction:.8,minViewportWidth:1200}]};expect(checkSceneCoverage(data,scene)).toEqual([{kind:'primary-point-label',minimumFraction:.8,numerator:3,denominator:8,fraction:.375}]);});

for(const backend of ['svg','canvas'])test(`pin verification natively selects visible topmost geometry in ${backend}`,async({page})=>{
 let html=(await fixtureHTML()).replace('id="mapsvg"',`id="mapsvg" data-renderer="${backend}"`);
 html=html.replace('<defs>', '<g class="hits" fill="none" stroke="transparent" stroke-width="14"><path class="hit" data-name="Offscreen" d="M-500,-300 L-200,-300"/><path class="hit" data-name="Underlying" d="M20,300 L480,300"/><path class="hit" data-name="Topmost" d="M20,300 L480,300"/></g><defs>');
 await page.setContent(html);await page.addScriptTag({content:await readFile('pipeline/labels/dist/browser.js','utf8')});
 await page.evaluate(async()=>{await mapLayout.ready;await mapLayout.whenSettled();window.nativePinClicks=0;mapLayout.svg.addEventListener('click',event=>{if(event.isTrusted)window.nativePinClicks++;const hit=mapLayout.renderer?.active?mapLayout.pickTrail(event.clientX,event.clientY):event.target.closest('.hit');if(hit)document.querySelector('[data-layout-details]').textContent=hit.dataset.name+' · Trail details';});});
 if(backend==='canvas')await page.evaluate(async()=>{mapLayout.beginGesture('pointer');mapLayout.requestView({x:100,y:100,w:300,h:240});await new Promise(requestAnimationFrame);});
 expect(await checkPinnedTrailDetails(page)).toEqual({trail:'Topmost'});
 expect(await page.evaluate(()=>window.nativePinClicks)).toBe(1);
 await page.locator('[data-layout-details]').evaluate(e=>e.style.display='none');await expect(checkPinnedTrailDetails(page)).rejects.toThrow('visible details');
});
test('destination coverage counts reviewed identity alternatives once and keeps every required core',()=>{
 const data={manifest:{annotations:[{id:'a',kind:'point-label'},{id:'alias',kind:'point-label'},{id:'b',kind:'point-label'}]},visible:['alias'],outcomes:[]};
 const scene={viewportWidth:1440,destinations:{minViewportWidth:1200,minimumFraction:.8,requiredMinimumFraction:1,groups:[{id:'first',annotationIds:['a','alias'],required:true},{id:'second',annotationIds:['b'],required:true}]}};
 const failures=checkSceneCoverage(data,scene);expect(failures).toContainEqual({kind:'reviewed-destinations',minimumFraction:.8,numerator:1,denominator:2,fraction:.5,missing:['second']});expect(failures).toContainEqual({kind:'required-destinations',minimumFraction:1,numerator:1,denominator:2,fraction:.5,missing:['second']});
 data.visible.push('b');expect(checkSceneCoverage(data,scene)).toEqual([]);data.visible=[];expect(checkSceneCoverage(data,{...scene,viewportWidth:360})).toEqual([]);
 expect(checkSceneCoverage(data,{...scene,destinations:{...scene.destinations,groups:[]}})).toContainEqual({kind:'reviewed-destinations',minimumFraction:.8,numerator:0,denominator:0,fraction:0,missing:[]});
 expect(checkSceneCoverage(data,{...scene,destinations:{...scene.destinations,groups:[{id:'unknown',annotationIds:['absent'],required:true}]}}).some(f=>f.missing.includes('unknown'))).toBe(true);
});
