import {test,expect} from '@playwright/test';
import {mkdtemp,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {releaseStates,checkSceneCoverage,runReleaseScenes} from '../../scripts/release-scenes.mjs';
import {summarizeCoverage} from '../../scripts/release-browser-audit.js';
import {runAudit} from '../../scripts/audit-map.mjs';
import {fixtureHTML} from '../support/browser-fixture.js';
test('release states deterministically include all tier sides and 250 random views',()=>{const a=releaseStates({width:1000,height:800,features:[]});expect(a).toEqual(releaseStates({width:1000,height:800,features:[]}));expect(a.filter(x=>x.kind==='random')).toHaveLength(250);for(const boundary of [1.02,2,4.5])for(const delta of [-.0001,0,.0001])expect(a.some(s=>Math.abs(s.zoom-boundary-delta)<1e-8)).toBe(true);expect(a.some(s=>s.zoom===14)).toBe(true);});
test('coverage minima detect hidden names even when solver claims pass',()=>{const data={manifest:{annotations:[{id:'a',kind:'point-label',priority:800}]},visible:[],outcomes:[{id:'a',reason:'placed'}]};expect(checkSceneCoverage(data,{minima:{'point-label':1}})).toEqual([{kind:'point-label',minimum:1,visible:0}]);});
test('quick release harness independently rejects overlapping miniature map',async()=>{const dir=await mkdtemp(join(tmpdir(),'map-release-'));try{const input=join(dir,'map.html');await writeFile(input,(await fixtureHTML()).replaceAll('visibility:hidden','visibility:visible').replaceAll('font-size:12px','font-size:6px')+'<img src="https://example.invalid/remote.png"><script>window.mapLayout={ready:Promise.resolve(),whenSettled:()=>Promise.resolve(),requestView:()=>{},result:{missingRequired:[]}};</script>');const r=await runReleaseScenes({input,reportDir:join(dir,'report'),browsers:['chromium'],viewports:[{width:768,height:1024}],dprs:[1],themes:['light'],states:[{id:'miniature',zoom:1,kind:'fixture'}],sampleCount:0,frameCount:2,interactions:false});expect(r.status,JSON.stringify(r.profiles)).toBe('findings');expect(r.counts.overlaps).toBeGreaterThan(0);expect(r.artifactSha256).toMatch(/^[a-f0-9]{64}$/);expect(r.releaseComplete).toBe(false);expect(r.profiles[0].networkFailures.some(f=>f.url.includes('example.invalid'))).toBe(true);expect(r.counts.incomplete).toBeGreaterThan(0);expect(r.counts.frames).toBe(6);expect(r.counts.typography).toBeGreaterThan(0);const audit=await runAudit({input,reportDir:join(dir,'audit'),mode:'managed'});expect(audit.counts.typography).toBeGreaterThan(0);for(const sample of r.profiles[0].samples){expect(sample.inventory).toBeUndefined();expect(sample.obstacles).toBeUndefined();expect(sample.counts.overlaps).toBeGreaterThan(0);}}finally{await rm(dir,{recursive:true,force:true});}});

test('desktop overview primary coverage uses eligible numerator and denominator',()=>{const data={manifest:{annotations:Array.from({length:10},(_,i)=>({id:String(i),kind:'point-label',priority:800}))},visible:['0','1','2'],outcomes:Array.from({length:10},(_,i)=>({id:String(i),eligible:i<8}))};const summary=summarizeCoverage(data);expect(summary['primary-point-label']).toEqual({visible:3,total:10,eligible:8,visibleEligible:3});const scene={viewportWidth:1440,fractions:[{kind:'primary-point-label',minimumFraction:.8,minViewportWidth:1200}]};expect(checkSceneCoverage(data,scene)).toEqual([{kind:'primary-point-label',minimumFraction:.8,numerator:3,denominator:8,fraction:.375}]);});
