import {test,expect} from '@playwright/test';
import {build} from 'esbuild';
let bundle;
test.beforeAll(async()=>{const r=await build({stdin:{contents:"export * from './pipeline/labels/line-candidates.js'; export {measureElement} from './pipeline/labels/measure.js'; export {solveLayout} from './pipeline/labels/place.js'; export {lineHitsRect} from './pipeline/labels/geometry.js';",resolveDir:process.cwd()},bundle:true,format:'iife',globalName:'lineAdapter',write:false});bundle=r.outputFiles[0].text;});
async function fixture(page){await page.setContent(`<svg width="600" height="400" viewBox="0 0 300 200"><path id="trail" d="M 20,150 L 260,30" fill="none" stroke="black"/><path id="curve" d="M 10,100 Q 150,60 280,100" fill="none"/><g id="straight"><g transform="translate(30,30) rotate(80)"><text text-anchor="middle" font-size="9">North Kaibab Trail</text></g></g><g id="curved"><text font-size="9" text-anchor="middle"><textPath href="#curve" startOffset="50%">Colorado River</textPath></text></g></svg>`);await page.addScriptTag({content:bundle});}
test('straight candidates follow real trail windows, cancel old angle and restore DOM',async({page})=>{await fixture(page);const r=await page.evaluate(()=>{const e=document.querySelector('#straight'),before=e.outerHTML,cs=lineAdapter.buildLineCandidates({annotation:{geometryIds:['trail']},element:e,policy:{maxLineCandidates:4}}),c=cs.find(c=>c.side!==0),restored=e.outerHTML===before;lineAdapter.applyLineCandidate(e,c);const actual=lineAdapter.measureElement(e),m=e.querySelector('text').getScreenCTM();return {count:cs.length,restored,actual,expected:c.shape,angle:Math.atan2(m.b,m.a)*180/Math.PI,side:c.side,application:c.application};});expect(r.count).toBeGreaterThan(2);expect(r.restored).toBe(true);expect(r.angle).toBeCloseTo(-26.565,1);expect(r.actual.bounds.x).toBeCloseTo(r.expected.bounds.x,3);expect(r.actual.bounds.y).toBeCloseTo(r.expected.bounds.y,3);expect(r.application.transform).toContain('matrix');});
test('curved candidates have full glyph footprints and restore original path offset',async({page})=>{await fixture(page);const r=await page.evaluate(()=>{const e=document.querySelector('#curved'),before=e.outerHTML,cs=lineAdapter.buildLineCandidates({annotation:{geometryId:'curve'},element:e,policy:{maxLineCandidates:4}}),restored=e.outerHTML===before;lineAdapter.applyLineCandidate(e,cs[0]);return {restored,count:cs.length,parts:cs[0].shape.parts.length,actual:lineAdapter.measureElement(e),expected:cs[0].shape,offset:cs[0].startOffset};});expect(r.restored).toBe(true);expect(r.count).toBeGreaterThan(2);expect(r.parts).toBeGreaterThan(5);expect(r.actual.bounds.x).toBeCloseTo(r.expected.bounds.x,3);expect(Number(r.offset)).toBeGreaterThan(0);});
test('short geometry yields no overflowing candidate and does not mutate text',async({page})=>{await fixture(page);expect(await page.evaluate(()=>{document.querySelector('#trail').setAttribute('d','M0,0 L2,0');const e=document.querySelector('#straight'),before=e.outerHTML;return {count:lineAdapter.buildLineCandidates({annotation:{geometryIds:['trail']},element:e}).length,restored:e.outerHTML===before};})).toEqual({count:0,restored:true});});
test('an initially overflowing curve still finds complete alternate windows',async({page})=>{await fixture(page);const r=await page.evaluate(()=>{const e=document.querySelector('#curved');e.querySelector('textPath').setAttribute('startOffset','120%');try{return {count:lineAdapter.buildLineCandidates({annotation:{geometryId:'curve'},element:e,policy:{maxLineCandidates:4}}).length,offset:e.querySelector('textPath').getAttribute('startOffset')};}catch(error){return {error:error.message};}});expect(r.count).toBeGreaterThan(0);expect(r.offset).toBe('120%');});
test('own-trail strokes stay protected while a measured side position supplies coverage',async({page})=>{await fixture(page);const r=await page.evaluate(()=>{document.querySelector('#trail').setAttribute('d','M20,100 L260,100');const e=document.querySelector('#straight'),cs=lineAdapter.buildLineCandidates({annotation:{geometryIds:['trail']},element:e,policy:{lineOffset:30,maxLineCandidates:2}}),m=document.querySelector('svg').getScreenCTM(),line={a:{x:20*m.a+m.e,y:100*m.d+m.f},b:{x:260*m.a+m.e,y:100*m.d+m.f},width:2},shape={bounds:{x:line.a.x,y:line.a.y-1,width:line.b.x-line.a.x,height:2},parts:[{x:line.a.x,y:line.a.y-1,width:line.b.x-line.a.x,height:2}]};const result=lineAdapter.solveLayout({annotations:[{id:'trail-name',featureId:'trail',required:true,candidates:cs}],obstacles:[{id:'trail',kind:'trail',line,shape}],viewport:{x:0,y:0,width:600,height:400}});return {missing:result.missingRequired,count:result.placements.length,side:result.placements[0]?.side,overlap:result.placements.some(p=>p.footprint.parts.some(r=>lineAdapter.lineHitsRect(line,r,2)))};});expect(r).toEqual({missing:[],count:1,side:1,overlap:false});});
test('rotated per-character footprints permit diagonal trail sides without covering its stroke',async({page})=>{await fixture(page);const r=await page.evaluate(()=>{const e=document.querySelector('#straight'),cs=lineAdapter.buildLineCandidates({annotation:{geometryIds:['trail']},element:e,policy:{maxLineCandidates:2}}),m=document.querySelector('svg').getScreenCTM(),line={a:{x:20*m.a+m.e,y:150*m.d+m.f},b:{x:260*m.a+m.e,y:30*m.d+m.f},width:2},parts=[{x:line.a.x,y:line.b.y-1,width:line.b.x-line.a.x,height:line.a.y-line.b.y+2}];const result=lineAdapter.solveLayout({annotations:[{id:'trail-name',required:true,candidates:cs}],obstacles:[{id:'trail',kind:'trail',line,shape:{bounds:parts[0],parts}}],viewport:{width:600,height:400}});return {missing:result.missingRequired,count:result.placements.length,parts:result.placements[0]?.footprint.parts.length,overlap:result.placements.some(p=>p.footprint.parts.some(r=>lineAdapter.lineHitsRect(line,r,2)))};});expect(r.missing).toEqual([]);expect(r.count).toBe(1);expect(r.parts).toBeGreaterThan(5);expect(r.overlap).toBe(false);});
test('cached matrix and translated footprint remain exact under camera pan',async({page})=>{await fixture(page);const r=await page.evaluate(()=>{const e=document.querySelector('#straight'),svg=document.querySelector('svg'),before=e.parentElement.getScreenCTM(),c=lineAdapter.buildLineCandidates({annotation:{geometryIds:['trail']},element:e,policy:{maxLineCandidates:1}})[1];svg.setAttribute('viewBox','10 15 300 200');const after=e.parentElement.getScreenCTM(),moved=lineAdapter.reprojectLineCandidate(c,before,after);lineAdapter.applyLineCandidate(e,moved);const actual=lineAdapter.measureElement(e);svg.setAttribute('viewBox','10 15 150 100');let error;try{lineAdapter.reprojectLineCandidate(c,before,e.parentElement.getScreenCTM());}catch(e){error=e.message;}return {actual:actual.bounds,expected:moved.shape.bounds,sameTransform:moved.transform===c.transform,error};});expect(r.actual.x).toBeCloseTo(r.expected.x,3);expect(r.actual.y).toBeCloseTo(r.expected.y,3);expect(r.sameTransform).toBe(true);expect(r.error).toContain('remeasure');});
test('authored polylines use their exact vertices without repeated DOM path scans',async({page})=>{
 await fixture(page);const result=await page.evaluate(()=>{
  const path=document.querySelector('#trail');let scans=0;const original=path.getPointAtLength.bind(path);path.getPointAtLength=(n)=>{scans++;return original(n);};
  const options={annotation:{geometryIds:['trail']},element:document.querySelector('#straight'),policy:{maxLineCandidates:2}};
  const first=lineAdapter.buildLineCandidates(options);path.setAttribute('d','M20,100 L20.1,100');const second=lineAdapter.buildLineCandidates(options);
  return {scans,first:first.length,second:second.length};
 });expect(result.first).toBeGreaterThan(0);expect(result.second).toBe(0);expect(result.scans).toBe(0);
});
test('straight trail names can sit beside a winding route without bending glyphs',async({page})=>{
 await fixture(page);const result=await page.evaluate(()=>{
  const path=document.querySelector('#trail');path.setAttribute('d','M20,100 '+Array.from({length:30},(_,i)=>`${28+i*8},${i%2?104:96}`).join(' '));
  const candidates=lineAdapter.buildLineCandidates({annotation:{geometryIds:['trail'],anchor:[140,100]},element:document.querySelector('#straight'),policy:{maxLineCandidates:8}});
  const numbers=path.getAttribute('d').match(/-?\d+(?:\.\d+)?/g).map(Number),m=path.getScreenCTM(),lines=[];
  for(let i=2;i<numbers.length;i+=2)lines.push({a:{x:numbers[i-2]*m.a+m.e,y:numbers[i-1]*m.d+m.f},b:{x:numbers[i]*m.a+m.e,y:numbers[i+1]*m.d+m.f},width:2});
  return {count:candidates.length,upright:candidates.every(c=>c.angle>=-90&&c.angle<=90),clear:candidates.some(c=>!lines.some(l=>c.shape.parts.some(r=>lineAdapter.lineHitsRect(l,r,2))))};
 });expect(result.count).toBeGreaterThan(0);expect(result.upright).toBe(true);expect(result.clear).toBe(true);
});
test('window budget is global across route parts and favors the nearest part',async({page})=>{
 await fixture(page);const result=await page.evaluate(()=>{
  const path=document.querySelector('#trail'),far=path.cloneNode();path.setAttribute('d','M20,100 L280,100');far.id='far';far.setAttribute('d','M20,20 L280,20');path.after(far);
  const cs=lineAdapter.buildLineCandidates({annotation:{geometryIds:['far','trail'],anchor:[140,100]},element:document.querySelector('#straight'),policy:{maxLineCandidates:2}});
  return {count:cs.length,first:cs[0].geometryId};
 });expect(result.count).toBeLessThanOrEqual(6);expect(result.first).toBe('trail');
});
