import {test,expect} from '@playwright/test';
import {collectTypography,checkTypography} from '../support/typography-audit.js';
async function fixture(page,body,annotation={},mode='interactive'){const a={id:'label',elementId:'label',featureId:'f',kind:'point-label',style:'l-place',anchor:[100,100],...annotation};await page.setContent(`<svg id="mapsvg" width="500" height="400"><g id="label">${body}</g></svg><script type="application/json" id="map-label-manifest">${JSON.stringify({map:{mode},annotations:[a]})}</script>`);return page.evaluate(collectTypography);}
test('effective primary font size cannot shrink beneath policy or inherit secondary size',async({page})=>{const d=await fixture(page,'<g transform="translate(100 100) scale(.5)"><text font-size="12">Camp<tspan font-size="8" dy="12">2,500 ft</tspan></text></g>');expect(checkTypography(d,{sizes:{place:12,secondary:10}}).some(f=>f.reason==='minimum-font-size'&&f.minimum===12)).toBe(true);});
test('line author rotation must remain upright',async({page})=>{const d=await fixture(page,'<text x="100" y="100" font-size="13" transform="rotate(150 100 100)">Trail</text>',{kind:'line-label',style:'l-trail'});expect(checkTypography(d,{}).some(f=>f.reason==='upside-down')).toBe(true);});
test('independent unconstrained advance detects overflowing curved text',async({page})=>{const d=await fixture(page,'<defs><path id="p" d="M100 100 L120 100"/></defs><text font-size="14"><textPath href="#p" startOffset="100%">Long river label</textPath></text>',{kind:'line-label',geometryId:'p',style:'l-river'});expect(checkTypography(d,{}).some(f=>f.reason==='text-path-overflow')).toBe(true);});
test('point paint cannot be arbitrarily displaced; hidden text is ignored',async({page})=>{const d=await fixture(page,'<text x="250" y="100" font-size="12">Camp</text>');expect(checkTypography(d,{}).some(f=>f.reason==='point-displacement')).toBe(true);await page.locator('#label').evaluate(e=>e.style.visibility='hidden');expect(checkTypography(await page.evaluate(collectTypography),{})).toEqual([]);});
test('static typography retains original positive font profile',async({page})=>{const d=await fixture(page,'<text x="100" y="100" font-size="8">Camp</text>',{},'static');expect(checkTypography(d,{sizes:{place:12}})).toEqual([]);});

test('wrapped primary tspans keep primary minimum',async({page})=>{const d=await fixture(page,'<text x="100" y="100" font-size="12"><tspan data-layout-primary="true" font-size="10">Long place</tspan></text>');expect(checkTypography(d,{})).toContainEqual({id:'label',reason:'minimum-font-size',size:10,minimum:12});});
test('point distance measures painted halo rather than unpainted text bounds',async({page})=>{const d=await fixture(page,'<text x="133" y="100" font-size="12" stroke="white" stroke-width="4">Camp</text>');expect(checkTypography(d,{}).filter(f=>f.reason==='point-displacement')).toEqual([]);});
