import test from 'node:test';
import assert from 'node:assert/strict';
import {solveLayout} from '../../pipeline/labels/place.js';
import {pointCandidates} from '../../pipeline/labels/candidates.js';
import {shapeIntersects} from '../../pipeline/labels/geometry.js';
import {shape,candidate as c,annotation as a,scene,impossibleRequiredScene} from '../support/layout-fixtures.js';
function safe(result){for(let i=0;i<result.placements.length;i++)for(let j=i+1;j<result.placements.length;j++)assert.equal(shapeIntersects(result.placements[i].footprint,result.placements[j].footprint,2),false);}
test('impossible required annotation returns explicit miss and blocker',()=>{const r=solveLayout(impossibleRequiredScene());assert.deepEqual(r.missingRequired,['required-stop']);assert.equal(r.placements.length,0);assert.equal(r.outcomes[0].reason,'no-valid-candidate');assert.deepEqual(r.outcomes[0].blockerIds,['control']);});
test('alternate anchors and approved variant maintain useful coverage',()=>{const r=solveLayout(scene([a('first',[c('near',20,20)]),a('second',[c('full',20,20),c('short',50,20,10,10,{variantId:'approved-short'})])]));assert.equal(r.placements.length,2);assert.equal(r.placements[1].variantId,'approved-short');safe(r);});
test('priority and stable IDs make source order irrelevant; optional conflict is recorded',()=>{const s=scene([a('z',[c('only',20,20)]),a('b',[c('only',20,20)],{priority:20}),a('a',[c('only',20,20)],{priority:20})]);const r=solveLayout(s);assert.deepEqual(r,solveLayout({...s,annotations:s.annotations.toReversed()}));assert.equal(r.placements[0].id,'a');assert.equal(r.outcomes.length,3);assert.equal(r.outcomes.find(o=>o.id==='z').reason,'collision');safe(r);});
test('previous candidate survives when valid but is rejected when blocked',()=>{const s=scene([a('a',[c('one',20,20),c('two',60,20)])]);s.previous={placements:[{id:'a',candidateId:'two'}]};assert.equal(solveLayout(s).placements[0].candidateId,'two');s.obstacles=[{id:'new',shape:shape(60,20)}];assert.equal(solveLayout(s).placements[0].candidateId,'one');});
test('bounded repair relocates an earlier label without dropping either',()=>{const r=solveLayout(scene([a('a',[c('first',20,20),c('alternate',80,20)],{required:true}),a('b',[c('only',20,20)],{required:true})]));assert.equal(r.placements.length,2);assert.equal(r.placements.find(p=>p.id==='a').candidateId,'alternate');assert.deepEqual(r.missingRequired,[]);safe(r);});
test('own symbols remain obstacles without an explicit relationship permission',()=>{const s=scene([a('name',[c('only',20,20)],{featureId:'same'})],[{id:'marker',featureId:'same',kind:'symbol',shape:shape(20,20)}]);assert.equal(solveLayout(s).placements.length,0);s.annotations[0].allowedObstacleIds=['marker'];assert.equal(solveLayout(s).placements.length,1);});
test('protected trails and frame clipping block labels',()=>{const s=scene([a('river',[c('trail',20,20),c('edge',-2,80),c('safe',80,80)])],[{id:'trail',kind:'trail',line:{a:{x:0,y:25},b:{x:100,y:25},width:2},shape:shape(0,24,100,2)}]);assert.equal(solveLayout(s).placements[0].candidateId,'safe');});
test('explicit group coverage, eligibility and repeat spacing are enforced',()=>{const s=scene([a('a',[c('a',20,20)],{requiredGroup:'main',featureId:'route',repeatDistance:80}),a('b',[c('b',60,20)],{requiredGroup:'main',featureId:'route',repeatDistance:80}),a('hidden',[],{eligibleReason:'zoom-tier'})]);s.policy.requiredGroups=['main','other'];const r=solveLayout(s);assert.equal(r.placements.length,1);assert.deepEqual(r.missingRequired,['route:other']);assert.equal(r.outcomes.find(o=>o.id==='hidden').reason,'zoom-tier');assert.equal(r.outcomes.find(o=>o.id==='b').reason,'repeat-spacing');});
test('point candidates include eight anchors, bounded alternatives and fixed symbols',()=>{const m=shape(90,90,20,10);const cs=pointCandidates({anchor:[100,100],kind:'poi'},m,{});assert.equal(cs[0].id,'preferred');assert.ok(cs.length>=9);assert.ok(cs.some(c=>c.shape.bounds.x>100));assert.ok(cs.some(c=>c.shape.bounds.x+c.shape.bounds.width<100));assert.deepEqual(pointCandidates({anchor:[100,100],kind:'symbol'},m,{}).map(c=>c.id),['preferred']);});
