"""Public facility semantics; lack of a drinking-water tag never implies potability."""
# Basic services have sufficient standardized glyphs: retain any supplied name
# for search/details, but do not repeat it as map text. Resolve the primary role
# first, so a campsite with toilets remains a named campsite.
SYMBOL_ONLY_SERVICES=frozenset(('toilets','bench','waste','telephone'))
RULES=[('highway','trailhead','th','Trailhead'),('tourism','camp_site','camp','Campground'),('tourism','wilderness_hut','shelter','Hut'),('amenity','shelter','shelter','Shelter'),('tourism','alpine_hut','shelter','Hut'),('amenity','toilets','toilets','Toilets'),('amenity','drinking_water','water','Mapped drinking-water point; availability unverified'),('natural','spring','spring','Spring; flow and water quality unverified'),('natural','waterfall','falls','Waterfall'),('waterway','waterfall','falls','Waterfall'),('amenity','parking','parking','Parking'),('tourism','information','info','Visitor information'),('tourism','hotel','lodge','Lodging'),('tourism','viewpoint','view','Viewpoint'),('amenity','ranger_station','ranger','Ranger station'),('amenity','restaurant','food','Food'),('amenity','cafe','food','Cafe'),('amenity','fuel','fuel','Fuel'),('shop','convenience','shop','Supplies'),('shop','supermarket','shop','Supplies'),('amenity','bench','bench','Bench'),('amenity','waste_disposal','waste','Waste disposal'),('amenity','waste_basket','waste','Waste bin'),('public_transport','platform','bus','Transit stop'),('highway','bus_stop','bus','Bus stop'),('natural','peak','peak','Summit'),('natural','saddle','saddle','Saddle'),('amenity','telephone','telephone','Telephone; service unverified'),('tourism','picnic_site','picnic','Picnic area'),('leisure','picnic_table','picnic','Picnic table'),('amenity','picnic_table','picnic','Picnic table'),('highway','crossing','crossing','Road crossing'),('highway','ford','ford','Ford; crossing conditions unverified'),('ford','yes','ford','Ford; crossing conditions unverified'),('barrier','gate','gate','Gate; access unverified'),('barrier','lift_gate','gate','Gate; access unverified'),('barrier','swing_gate','gate','Gate; access unverified'),('barrier','toll_booth','gate','Access barrier; current operation unverified'),('barrier',None,'barrier','Barrier; access unverified'),('historic',None,'historic','Historic feature')]
def poi_style(tags):
 if tags.get('ford') not in (None,'no'):return {'symbol':'ford','description':'Ford; crossing conditions unverified','maxMetersPerPixel':12}
 for key,value,symbol,description in RULES:
  if tags.get(key) is not None and (value is None or tags[key]==value):return {'symbol':symbol,'description':description,'maxMetersPerPixel':32 if symbol in ('peak','camp','th','spring','falls','view','lodge') else 6 if symbol in ('bench','waste') else 12}
 return {'symbol':'point','description':'Named feature','maxMetersPerPixel':24}
